/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bully;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author yohov
 */
public class BullyGUI extends javax.swing.JFrame {

	/**
	 * Creates new form BullyGUI
	 */
	public BullyGUI() {
		initComponents();
		addTexto();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTAMensajes = new javax.swing.JTextArea();
        jTFNP = new javax.swing.JTextField();
        JBtnAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBTNIniciar = new javax.swing.JButton();
        JTFPI = new javax.swing.JTextField();
        JLBCoordinador = new javax.swing.JLabel();
        JBTNNP = new javax.swing.JButton();
        JBTNFalla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(528, 356));
        setMinimumSize(new java.awt.Dimension(528, 356));
        setResizable(false);
        setSize(new java.awt.Dimension(528, 356));

        JTAMensajes.setEditable(false);
        JTAMensajes.setColumns(20);
        JTAMensajes.setRows(5);
        jScrollPane1.setViewportView(JTAMensajes);

        jTFNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNPActionPerformed(evt);
            }
        });

        JBtnAceptar.setText("Aceptar");
        JBtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnAceptarActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero de Procesos:");

        jLabel2.setText("iniciar con el proceso:");

        jBTNIniciar.setText("Iniciar");
        jBTNIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNIniciarActionPerformed(evt);
            }
        });

        JLBCoordinador.setText("Coordinador:");

        JBTNNP.setText("Nuevo Proceso");
        JBTNNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNNPActionPerformed(evt);
            }
        });

        JBTNFalla.setText("Falla Coordinador");
        JBTNFalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTNFallaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBtnAceptar)
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jTFNP)
                                    .addComponent(jLabel2)
                                    .addComponent(JTFPI, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jBTNIniciar))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JLBCoordinador))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JBTNFalla)
                                    .addComponent(JBTNNP))))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBtnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jBTNIniciar)
                        .addGap(27, 27, 27)
                        .addComponent(JBTNNP)
                        .addGap(18, 18, 18)
                        .addComponent(JBTNFalla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JLBCoordinador)
                        .addGap(31, 31, 31))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnAceptarActionPerformed
        // TODO add your handling code here:
		if(this.jTFNP.getText().matches("[0-9]+")){
			int aux = Integer.parseInt(jTFNP.getText());
			for(int i=0;i<aux;i++){
				this.Ids.add(i);
				this.Estados.add(true);
				this.Mensajes.add(0);
			}
			for(int i=0;i<aux;i++){
				this.procesos.add(new Proceso(Ids,i,Estados,coord,Mensajes,m));
			}
			for(int i=0;i<aux;i++){
				this.procesos.get(i).start();
			}
			this.JBtnAceptar.setEnabled(false);
			this.jTFNP.setEnabled(false);
		}else{
			JOptionPane.showMessageDialog(null,"Caracter no valido"); 
		}
		
    }//GEN-LAST:event_JBtnAceptarActionPerformed

    private void jTFNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNPActionPerformed
        // TODO add your handling code here:
		
    }//GEN-LAST:event_jTFNPActionPerformed

    private void jBTNIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNIniciarActionPerformed
        // TODO add your handling code here:
		if(this.JTFPI.getText().matches("[0-9]+")){
			int aux = Integer.parseInt(JTFPI.getText());
			if(aux < procesos.size()){
				this.procesos.get(aux).coordinador();
				this.jBTNIniciar.setEnabled(false);
				this.JTFPI.setEnabled(false);
			}else{
				JOptionPane.showMessageDialog(null,"Indice no valido"); 
			}
		}else{
			JOptionPane.showMessageDialog(null,"Caracter no valido"); 
		}
		
		
    }//GEN-LAST:event_jBTNIniciarActionPerformed

    private void JBTNNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNNPActionPerformed
        // TODO add your handling code here:
		this.coord[0]=-1;
		this.Ids.add(this.Ids.size());
		this.Estados.add(true);
		this.Mensajes.add(0);
		this.procesos.add(new Proceso(Ids,Ids.size()-1,Estados,coord,Mensajes,m));
		this.procesos.get(Ids.size()-1).start();
		this.procesos.get(Ids.size()-1).abusivo();
    }//GEN-LAST:event_JBTNNPActionPerformed

    private void JBTNFallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTNFallaActionPerformed
        // TODO add your handling code here:
		this.procesos.get(coord[0]).matarProceso();
		Random r = new Random();
		int aux = r.nextInt(this.procesos.size()-1);
		if(aux != this.coord[0]){
			this.coord[0]=-1;
			for(int i=0;i<this.procesos.size();i++){
				this.procesos.get(i).setEnvio(false);
				this.Mensajes.set(i, 0);
			}
			this.procesos.get(aux).coordinador();
		}
    }//GEN-LAST:event_JBTNFallaActionPerformed

	public void addTexto(){
		Runnable r = new Runnable() {
			@Override
			public void run() {
				while(true){
					String aux="";
					for(int i=0;i<m.size();i++){
						aux+=m.get(i)+"\n";
					}
					JTAMensajes.setText(aux);
					JLBCoordinador.setText("Proceso Coordinador: "+coord[0]);
				}
			}
		};
		Thread t = new Thread(r);
		t.start();
	}
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(BullyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(BullyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(BullyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(BullyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new BullyGUI().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTNFalla;
    private javax.swing.JButton JBTNNP;
    private javax.swing.JButton JBtnAceptar;
    private javax.swing.JLabel JLBCoordinador;
    private javax.swing.JTextArea JTAMensajes;
    private javax.swing.JTextField JTFPI;
    private javax.swing.JButton jBTNIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFNP;
    // End of variables declaration//GEN-END:variables
	ArrayList<Integer> Ids = new ArrayList();
	ArrayList<Boolean> Estados = new ArrayList();
	ArrayList<Integer> Mensajes = new ArrayList();
	ArrayList<String> m = new ArrayList();
	ArrayList<Proceso> procesos = new ArrayList();
	int coord[] = {-1,0,0};
}
